import '@/styles/globals.css'
import { notojp } from '@/libs/font'
import { Providers } from '@/store/Provider'
import BottomNavbar from './_components/Common/BottomNavbar'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${notojp.variable}`}>
      <body className="h-screen bg-back font-notojp">
        <Providers>
          {children}
          <BottomNavbar />
        </Providers>
        <div className="h-20"></div>
      </body>
    </html>
  )
}
