import '@/styles/globals.css'
import { notojp } from '@/libs/font'
import { Providers } from '@/store/Provider'
import { BottomNavbarContainer } from './_components/Common/BottomNavbar'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${notojp.variable}`}>
      <body className="h-screen bg-background font-notojp ">
        <Providers>
          {children}
          <BottomNavbarContainer />
        </Providers>
      </body>
    </html>
  )
}
